quoite = "Думаю. на мировом рынке можно будет продать штук пять компьютеров."
print("Исходная цитата:")
print(quoite)
print("\nOнa же в верхнем регистре:")
print(quoite.upper())
print("\nB нижнем регистре:")
print(quoite.lower())
print("\nKaк заголовок:")
print(quoite.title())
print("\nма-а-аленькой заменой:")
print(quoite.replace("штyк пять","несколько миллионов"))
print("\n A вот опять исходная цитата:")
print(quoite.capitalize())
print(quoite.swapcase())
print(quoite.strip())
input("\nHaжмитe Enter. чтобы выйти")